### ISSUE TITLE
Running rexster + doghouse on different baseurl

### ISSUE THREAD

**Issue by vossim** [tinkerpop/rexster#350]
Running rexster and doghouse on something else than a root url does not seem to be possible. It would be great if we could configure the application to run under "http://[INSERT_IP_HERE]:8182/rexster" or some other context-path, I've tried updating the base-url configuration parameter, but it ends up trying to run on "http://[INSERT_IP_HERE]/rexster:8182".

**Comment by ti-mo** [comment]
Hi, @spmallette, any word on this please? This prevents REST calls from being proxied, making it inaccessible from an internet desert. :(

**Comment by angelcervera** [comment]
Hi @vossim 
Maybe you want to said http://localhost:8182/rexster and not http://localhost/rexster:8182
The port must be always next of the host and before the context.

Regards.

**Comment by spmallette** [comment]
@ti-mo   I've been mostly focused on TinkerPop3 development in recent times and haven't done much with Rexster as we are mostly in maintenance mode when it comes to TinkerPop2 lines of code.  I'm not sure when I'll get back to Rexster unless there is some sort of major bug.  It seems like at least a few people want this change in place though, so I'll have to see what the impact is of implementing it.  I have a feeling I did actually look at it a while back and deemed it more than I felt comfortable for "maintenance".

**Comment by MMaas3** [comment]
The last few weeks a colleague and I encountered the same problem. The solution I would like to see is that the base-uri is independent of the server-port. Maybe add a configuration option to configure the port of the base-uri, or configure the port as part of the base-uri.

**Comment by spmallette** [comment]
Fixed via #389
