### ISSUE TITLE
build failed to find com.tinkerpop.blueprints:blueprints-core:jar:2.5.0-SNAPSHOT

### ISSUE THREAD

**Issue by kylehr** [tinkerpop/rexster#382]
Hi,

Apologies if this is an obvious one but this is my first foray into Maven :)

I downloaded the zip today from https://github.com/tinkerpop/rexster/tree/neo4j2.

It could not find this dependency and sure enough when I go to [central](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.tinkerpop.blueprints%22%20AND%20a%3A%22blueprints-core%22) I can see 2.5.0 but not 2.5.0-SNAPSHOT.

Am I missing something here?

Thank you.

Regards,
Kyle

**Comment by spmallette** [comment]
SNAPSHOTs are not in central - they are in sonatype:

https://oss.sonatype.org/content/repositories/snapshots/

Of course we have a stable release of 2.5.0 in central, so I don't think you'll find SNAPSHOT jars for that version anymore.  I'm not sure about the usefulness of that branch you are trying to download as well.  I think we were just testing out some things there with neo4j2 - that branch should probably be removed.  Please download the official Rexster 2.5.0 distribution itself and work with that.
