### ISSUE TITLE
Error: Could not get list of graphs from Rexster

### ISSUE THREAD

**Issue by thomasMary** [tinkerpop/rexster#384]
Hi,
When I access the doghouse (http://aa.bb.cc.dd:8182/doghouse) I've the following error:
     
           Error: Could not get list of graphs from Rexster

Note that when I access http://aa.bb.cc.dd:8182/graphs I've got the expected result:

      {"version":"2.6.0","name":"Rexster: A Graph Server","graphs":    ["mytitan"],"queryTime":0.43158,"upTime":"0[d]:00[h]:17[m]:37[s]"}

I've read that this problem can occur if one tries to access doghouse from an URI other than the base URI set in rexster.xml. Here is mine:

       <rexster>
         <http>
           <server-port>8182</server-port>
           <server-host>0.0.0.0</server-host>
           <base-uri>aa.bb.cc.dd</base-uri>
           <web-root>public</web-root>
           <character-set>UTF-8</character-set>
           <enable-doghouse>true</enable-doghouse>
           ...

As specified in the [doc](https://github.com/tinkerpop/rexster/wiki/Rexster-Configuration), both server (Titan & rexster) are running on the same machine.
Do you know what i'm doing wrong ? Thanks

**Comment by spmallette** [comment]
I suspect your config should be as follows:

    <base-uri>http://aa.bb.cc.dd</base-uri>

please let me know if that solves your problem.

**Comment by thomasMary** [comment]
Yes it does ! :) Thanks for that quick answer
