### ISSUE TITLE
Variable assignment Gremlin Extension Question

### ISSUE THREAD

**Issue by marcusbb** [tinkerpop/rexster#386]
I'm trying to use the gremlin extension with a variable assignment. Is this possible?
In my testing (I've removed the URL encoding in second line for readability)
tp/gremlin?script=
v=g.addVertex()
v.addProperty('name','value')

But throws
"message":"","error":"javax.script.ScriptException: groovy.lang.MissingMethodException: No signature of method: groovy.lang.MissingMethodException.addPropertery()

**Comment by spmallette** [comment]
I think you need `setProperty(k,v)`:

http://www.tinkerpop.com/docs/javadocs/blueprints/2.6.0/com/tinkerpop/blueprints/Element.html#setProperty(java.lang.String, java.lang.Object)

There is no `addProperty` in Blueprints.

**Comment by marcusbb** [comment]
Thanks I think I solved my issue, I think it was encoding related.
Actually both work -addProperty and setProperty - I'm working with a titan implementation.
